Question 1: Part  A: reqriting the fib_rec code as an iteration

In [10]:
# Professor's Fibanocci code.
def fib_rec(n):
    if n == 0:
        return 1
    elif n == 1:
        return 1
    else:
        return fib_rec(n-1)+fib_rec(n-2)


In [11]:
fib_rec(3)

3

In [18]:
# My fib Fibonacci sequence iterative implementation
def fib_iter(n):
    if n == 0:
        return 1
    elif n == 1:
        return 1
    else:
        print(0)

    a,b = 0,1
    for i in range(2,n+1):
        print(b)
        a, b = b, a + b
    return b


In [19]:
# Fib_iter check. 
fib_iter(6)

0
1
1
2
3
5


8

In [20]:


%%time
# Check CPU times of fibonacci iterative function
for n in range(100):
    fib_iter(10)

0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5

Part B: The iterative function is typically faster than the recursive version for larger values of n. This is because the recursive function computes the same Fibonacci number multiple times without storing which leads to a lack of memorization. This results leads to an exponential growth in computation time (O(2^n)). The iterative approach  computes each Fibonacci number exactly once, making it O(n) in time complexity.

Part C: 

In [21]:
import time 


def timer(func, n, k):
    
    runtimes = []
    for _ in range(k):
        start_time = time.time()
        func(n)   
        end_time = time.time()
        runtime = end_time - start_time
        runtimes.append(runtime)

    average_time = sum(runtimes) / k
    return average_time

Part 4: plotting the fib_rec

In [23]:
import matplotlib.pyplot as plt

n_values = range(10,21)

k = 10

times_recursive = [timer(fib_rec, n, k) for n in n_values]
times_iterative = [timer(fib_iter, n, k) for n in n_values]

# Plotting
plt.figure(figsize=(10, 5))
plt.plot(n_values, times_recursive, label='Recursive Fibonacci', marker='o')
plt.plot(n_values, times_iterative, label='Iterative Fibonacci', marker='o')
plt.xlabel('n (Fibonacci Index)')
plt.ylabel('Average Time (seconds)')
plt.title('Comparative Execution Time of Fibonacci Functions')
plt.legend()
plt.grid(True)
plt.show()



0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34
55
89
144
0
1
1
2
3
5
8
13
21
34

Question 2: Part A. Linalg sequences
Given the Matrix below answer the questions: Find the determinant, transpose, inverse(if exist) for M.
M =(
1 −4 2
−4 1 −2
2 −2 −2)

In [ ]:
import numpy as np

M = np.array([[1,-4,2], [-4,1,-2], [2,-2,-2]])

# Determinant
det_M = np.linalg.det(M)

# Transpose 
# Nothing to transpose? 
transpose_M = M.T


# Inverse
inverse_M = np.linalg.inv(M) if np.linalg.det(M) != 0 else "Inverse does not exist"

print("Original:\n", M)
print("Determinant:", det_M)
print("Transpose:\n", transpose_M)
print("Inverse:\n", inverse_M)



Original:
 [[ 1 -4  2]
 [-4  1 -2]
 [ 2 -2 -2]]
Determinant: 54.00000000000001
Transpose:
 [[ 1 -4  2]
 [-4  1 -2]
 [ 2 -2 -2]]
Inverse:
 [[-0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -0.11111111 -0.11111111]
 [ 0.11111111 -0.11111111 -0.27777778]]


Part 2: eigenvalues and eigenvectors

In [ ]:
from numpy.linalg import eig

w,v = eig(M)
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [-3.  6. -3.]
Eigenvectors: [[-0.74535599 -0.66666667 -0.12593955]
 [-0.59628479  0.66666667  0.34003189]
 [ 0.2981424  -0.33333333  0.93194288]]


Part 3: Finding the Gradient value for the equation.

In [ ]:
# import everything from sympy import *
from sympy import *
import sympy as sp

# Define symbols
x11, x12, x13, x21, x22, x23, x31, x32, x33 = sp.symbols('x11 x12 x13 x21 x22 x23 x31 x32 x33')

# Define the function
f =(x11**2*x22*x23) + (x11*x12*x13*x31) - (x33**2*x32*x21)

# Compute gradient
A = sp.Matrix([[x11, x12, x13], [x21, x22, x23], [x31, x32, x33]])

gradient = [sp.diff(f, var) for var in A]

print("Gradient:\n", Matrix(3, 3, gradient))



Gradient:
 Matrix([[2*x11*x22*x23 + x12*x13*x31, x11*x13*x31, x11*x12*x31], [-x32*x33**2, x11**2*x23, x11**2*x22], [x11*x12*x13, -x21*x33**2, -2*x21*x32*x33]])


Part 4: Hessian Matrix

In [ ]:
x, y, z = sp.symbols('x y z')

g = x**3*y + y*z*sin(x) + x*y**2*z**5

# Compute Hessian
hessian = sp.hessian(g, (x, y, z))

hessian



Matrix([
[          6*x*y - y*z*sin(x), 3*x**2 + 2*y*z**5 + z*cos(x), 5*y**2*z**4 + y*cos(x)],
[3*x**2 + 2*y*z**5 + z*cos(x),                     2*x*z**5,   10*x*y*z**4 + sin(x)],
[      5*y**2*z**4 + y*cos(x),         10*x*y*z**4 + sin(x),         20*x*y**2*z**3]])

Question 3: Machine Learning
Part A: Validation samples are used during the model training process to fine-tune model parameters and prevent overfitting. Test samples are used post-model training to assess the performance of the model in an unbiased manner.
Part B: Supervised learning involves training a model on labeled data. Unsupervised learning involves training a model on data without labels to discover patterns or structures in the data.
Part C: Optimization in machine learning refers to the process of adjusting the parameters of models to minimize a cost function, which measures how well the model performs on training data. It's crucial for learning the best parameters that make a model fit the data well.

Question 4: 
I want to learn different types of machine learning programs. I would to get more experience using ML models for a variety types of datasets. I would like to get as much practice as possible. 